[project]
name = "ragagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thinlimbscoding-maker", email = "thinlimbscoding@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.0.10",
    "langchain>=1.4.3",
    "langchain-mcp-adapters>=0.3.1",
    "numpy>=2.5.3",
    "requests>=2.34.2",
    "rich>=15.0.0",
]

[project.scripts]
ragagent = "ragagent:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
